name: authenticationapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.13.1
  the_apple_sign_in: ^1.1.1
  device_preview: ^1.1.0
  firebase_storage: ^11.0.0
  image_picker: ^1.0.0
  image_picker_web: ^2.1.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  webview_flutter: ^4.2.2
  flutter_inappwebview: ^6.0.0
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.2
  flutter_spinkit: ^5.2.1
  google_generative_ai: ^0.4.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  uuid: ^4.4.0
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/image.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/splash.png
    - assets/videos/food_etiquette.mp4
    - assets/videos/brushing_teeth.mp4
    - assets/videos/washing_hands.mp4
    - assets/videos/wearing_shoes.mp4
    - assets/videos/feeling.mp4
    - assets/videos/others.mp4
    - assets/videos/helping.mp4
    - assets/videos/w1.jpg
    - assets/videos/w2.jpg
    - assets/videos/w3.jpg
    - assets/videos/fear.jpg
    - assets/videos/shok.jpg
    - assets/videos/happy.jpg
    - assets/videos/bad.jpg
    - assets/videos/sad.jpg
    - assets/
    - assets/videos/shape.mp4
    - assets/videos/animal.mp4
    - assets/videos/environ.mp4
    - assets/videos/english.mp4
    - assets/videos/arabic.mp4
    - images/image.png
    - assets/videos/number.mp4
    - assets/videos/minus.mp4
    - assets/videos/plus.mp4
    - assets/html/ar/
    - assets/html/callees/
    - assets/html/dr/
    - assets/html/vr/
    - assets/html/index.html
    - assets/html/goodbye.html
    - assets/videos/color/r.jpg
    - assets/videos/color/b.jpg
    - assets/videos/color/w.jpg
    - assets/videos/color/y.jpg
    - assets/videos/color/br.jpg
    - assets/videos/color/bi.jpg
    - assets/videos/color/g.jpg
    - assets/videos/color/bl.jpg
    - assets/videos/wash_hands/1.jpg
    - assets/videos/wash_hands/2.jpg
    - assets/videos/wash_hands/3.jpg
    - assets/videos/wash_hands/4.jpg
    - assets/videos/wash_hands/5.jpg
    - assets/videos/shose/1.jpg
    - assets/videos/shose/2.jpg
    - assets/videos/shose/3.jpg
    - assets/videos/shose/4.jpg
    - assets/videos/shose/5.jpg
    - assets/videos/food/1.jpg
    - assets/videos/food/2.jpg
    - assets/videos/food/3.jpg
    - assets/videos/food/4.jpg
    - assets/videos/food/5.jpg
    - assets/videos/food/6.jpg
    - assets/videos/food/7.jpg
    - assets/videos/food/8.jpg
    - images/ai.png
    - images/default_profile.png
    - images/2.png
    - images/1.jpg
    - images/22.png
    - images/image.png
